safe:       true
lsi:        false
pygments:   true
source:     _src
baseurl:    /button
plugins:    _src/_plugins

icon_meta:          _src/icons.yml
icon_layout:      	icon.html    # Relative to _layouts directory
icon_destination: 	icon         # Relative to destination
permalink:          pretty
destination:        _gh_pages

bootstrap:
    version:    3.0.0
    url:            http://getbootstrap.com

jquery:
    version:        1.10.2

button:
    license:        MIT Licence
    version:        1.0.0
    minor_version:  1.0
    url:            http://rogelio-meza-t.github.com/button/
    legacy_url:     http://rogelio-meza-t.github.com/button/
    blog_url:       http://rogelio-meza-t.github.com/button/
    twitter:        rogelio_meza
    tagline:        Get JSON responses easily
    css_prefix:     fa
    author:
        name:         Rogelio Meza
        email:        rogelio.meza.t@gmail.com
        twitter:      rogelio_meza
        work:
            name:       Leaf
            url:        http://leaf.cl
            title:      CEO
    github:
        url:          https://github.com/rogelio-meza-t/button
        project:      button
        org:          button